### ISSUE TITLE
Cloudflare no Virignia regionCode

### ISSUE THREAD

**Issue by news-emil-davidkov** [ampproject/cdn-worker#207]
Hey guys,
as more and more states introduce their type of CCPA/GDPR compliance, we have some projects that are AMP based and rely on amp-geo to provide the correct location for amp-consent and our CMP to do its thing.
In order to test that everything is mapped correctly, I've been using some VPN software (NordVPN) - pointing it to California, everything works as expected, amp-geo picks up the correct country and regionCode -
`text.replace(
      '{{AMP_ISO_COUNTRY_HOTPATCH}}',
      injectIsoCode.toLowerCase().padEnd(28)
    ),
    response`
 This seems to replace it just fine.
 Whenever I try change my location to Virginia(with the VPN), I cannot get the regionIso appear for the love of me. This got me to wonder if it is some restriction in the CDN or am I going insane ?

**Comment by danielrozenberg** [comment]
Can you please tell me which CDN you're testing? Are you using `https://cdn.ampproject.org/` (hosted on Google and is _not_ open source) or `https://ampjs.org/` (hosted on Cloudflare and is this CDN)

The Cloudflare-hosted CDN is not entirely launched yet (although it should be working correctly, the AMP validator code isn't set up yet to recognize it). If the problem is with the Google-hosted CDN I can try to forward this issue report to the relevant team at Google

Do note that due to the Christmas and New Year holidays, it's highly unlikely that we'll get a response before January

**Comment by news-emil-davidkov** [comment]
Hey, my bad, it is `https://cdn.ampproject.org/`.
My gut feeling is that it is a VPN issue, although its working fine for Cali...
Thanks for the reply!
